server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5957/tLDxDfwAf
    username: sjfFj31@ks!#_jk098s
    password: f3890@#jJS8F9sw_*j
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  secret: 357538782F413F4428472B4B6250655368566D59713374367639792442264529